Remove coveralls token from root.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -112,7 +112,14 @@ jobs:
       run: |
         python -m coverage xml -o coverage.xml -i
         python -m codecov -n 'lnx-${{ matrix.python-version }}-${{ matrix.tox-env }}${{ matrix.noipv6 }}' -X search -X gcov -f coverage.xml
+
+    - name: Publish coveralls
+      # We want to publish coverage even on failure.
+      if: contains(matrix['tox-env'], 'withcov') || failure()
+      run: |
         python -m coveralls
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
 
 
   pypi-publish:
